apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/postgres-data
---
# Persistente volume claim 5Gib
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi